### ISSUE TITLE
Allow adding text to camera output

### ISSUE THREAD

**Issue by timitoc** [AndreeaDogaru/COW#28]
Create a plugin for adding text. It can be similar to subtitles and complement the reacts feature.

**Comment by deathsurgeon1** [comment]
Hi @AndreeaDogaru , is this requirement related to showing speech to text on screen when user starts recording?

**Comment by AndreeaDogaru** [comment]
Hi! This plugin should allow the user to add and change a text message displayed over the camera output, similarly to the reactions plugin. The feature is not necessarily connected to the recording plugin, but the text should be captured in the recording. Regarding the speech-to-text feature, I think it is a good idea. However, it is a different feature, so I created a new issue for it #39.
